---
- hosts: devserver
  become: yes
  ignore_errors: yes
  vars:
    username: carol
    pkg_name: httpd
  tasks:
    - name: Creating user
      user:
        name: "{{username}}"
        comment: carol Admin
        shell: /bin/bash
    - name: Creating a group
      group:
        name: manager
        state: present 
          #      when: ansible_os_family == "Debian" 
    - name: creating a file
      file:
         path: /tmp/ansible.txt
         state: touch
         mode: '0600'
    - name: creating a directory
      file: 
         path: /tmp/dir
         state: directory
         mode: '0777'
    - name: Install apache
      yum:
         name: "{{pkg_name}}"
         state: latest 
    - name: install finger
      package:
        name: "{{ itme}}"
        state: present 
      with_items:
         - wget
         - samba
         - java-8*
         - finger     
